var data = {
    "en": {
        "1": "Our Services",
        "2": "About Us",
        "3": "Maintenance",
        "4": "Support Maintenance",
        "5": "Contacts",
        "6": "Software Development",
        "7": "We solve problems associated with performance, expandability, scalability, security and resiliency.",
        "8": "Our services",
        "9": "Our Services",
        "10": "Software development from scratch",
        "11": "Maintenance of individual stages of the client's project",
        "12": "Software Maintenance Services",
        "13": "Consulting services",
        "14": "About Us",
        "15": "Our specialists develop software using various technologies:",
        "16": "We assist with all individual stages of your project",
        "17": "Stage",
        "18": "We create software specifically tailored to your business.",
        "19": "We make necessary adjustments to operating systems.",
        "20": "We integrate apps.",
        "21": "We help you switch to more relevant or popular software products.",
        "22": "We solve problems associated with performance, expandability, scalability, security and resiliency.",
        "23": "We modify existing products to the currently necessary level.",
        "24": "We synchronize the operation of various systems with each other.",
        "25": "Maintaining your software",
        "26": "Around the clock technical support",
        "27": "We eliminate errors and defects that were detected during the process, making changes to the finished system",
        "28": "Professional audit",
        "29": "Analysis of the technical solution for compliance with non-functional requirements, studying the sequence of approaches and searching for ways to optimize them",
        "30": "Detailed documentation",
        "31": "Writing technical documentation and its adaptation",
        "32": "Multilevel testing",
        "33": "Verification of the developed solution by the customer, in accordance with expectations, thus creating a list of necessary changes",
        "34": "Contacts",
        "35": "Advertecy"
    },
    "ru": {
        "1": "Наши услуги",
        "2": "О нас",
        "3": "Сопровождение",
        "4": "Поддержание&nbsp;ПО",
        "5": "Контакты",
        "6": "Разработка программного обеспечения",
        "7": "Решим проблемы, связанные с производительностью, расширяемостью, масштабируемостью, безопасностью и отказоустойчивостью.",
        "8": "Наши услуги",
        "9": "Наши услуги",
        "10": "Разработка программного обеспечения с нуля",
        "11": "Сопровождение отдельных этапов проекта клиента",
        "12": "Услуги по поддержанию&nbsp;ПО",
        "13": "Консультационные услуги",
        "14": "О нас",
        "15": "Наши специалисты разрабатывают&nbsp;ПО с использованием различных технологий:",
        "16": "Сопроводим отдельные этапы вашего проекта",
        "17": "Этап",
        "18": "Мы создадим&nbsp;ПО с учетом специфики вашего бизнеса.",
        "19": "Внесем корректировки в работающие системы.",
        "20": "Произведем интеграцию приложений.",
        "21": "Поможем вам перейти на более актуальные или популярные программные продукты.",
        "22": "Решим проблемы, связанные с производительностью, расширяемостью, масштабируемостью, безопасностью и отказоустойчивостью.",
        "23": "Доработаем имеющиеся продукты до современного уровня.",
        "24": "Синхронизируем работу различных систем друг с другом.",
        "25": "Поддержание вашего&nbsp;ПО",
        "26": "Круглосуточная техподдержка",
        "27": "Устранение ошибок и дефектов, которые были обнаружены в ходе использования решения, занесение изменений в готовую систему",
        "28": "Профессиональный аудит",
        "29": "Анализ технического решения на предмет соответствия не функциональным требованиям, изучение последовательности подходов и поиск способов их оптимизации",
        "30": "Детальное документирование",
        "31": "Написание технической/сопроводительной документации и ее адаптация",
        "32": "Многоуровневое тестирование",
        "33": "Проверка заказчиком разработанного решения на соответствие ожиданиям, создание списка необходимых изменений",
        "34": "Контакты",
        "35": "Advertecy"
    }
}